language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction

script:
    - cd $TRAVIS_BUILD_DIR
    - vendor/bin/phpunit -c test/phpunit.xml --coverage-clover=./build/clover.xml
    - vendor/bin/phpcs --standard=PSR2 -s -p src/

after_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload build/clover.xml --format=php-clover; fi

notifications:
    slack:
      secure: mhS8IPczQWVzvamJZjETUaQ1cdwkaLV0dkejdZBg+7ZGnvCGBDuGDCDml0GAtmm80fctTONkQtGLn8RFOkI9EQaAwSdDYlsfN+FNocwSbxBmxQfzxwZRUb66oQJqHPdDTWdE7Ya2jCN6QhenlRiyYoHRd8lIQ2zxF0Klvklg8MbC0dE+qJOG0Xq04VvOM9ARamTkxTvSW8eH/PWSHT/bBRQ3DSTXN+7l25JR4kvKTSHielVjr1M5LUk+C8JEW18c1sBOH232a8NxVva1G2dI866KwLZUdcQGWkJpP2GhrTipgG1S8hXCzqPAcw02HkHsZrz3/fcMUpEMzogXwyzEszpoO5rUCecDnPkhdQpfcvAdahAYHSS+DmqjfGQG3w/i4tQ2CD3OLuTw2G8oSxwLkXaaQHJ+0VwiYMS39BySfZTwi6ul8TYr6kOA5hMdgm/3H0YGvuSJ6H6qwyObDacdKBlSIVzkReNEL7FNCgSG8+8iogT4q5SOr1JrBWPAskbKdFZgXyUyPO4YMO9qL6akulOSugDPmVYawZkv1fJ+CpKXLyzylCt3zoj0FYcjUEZQNpKrqpcCGeLTHzFCGbvnLHj7RlEyaNpk4HLPwFozs0VoLMwAJwSNk9PaCwj7VHT6AV/yD5rH6EJMQ2UWuHdP9x+qoF42lsPoCoJd74QEkbA=

